/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.pharbers.kafka.schema;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class FileMetaData extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 7594688798061715130L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"FileMetaData\",\"namespace\":\"com.pharbers.kafka.schema\",\"fields\":[{\"name\":\"JobId\",\"type\":\"string\"},{\"name\":\"MetaDataPath\",\"type\":\"string\"},{\"name\":\"SampleDataPath\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence JobId;
  @Deprecated public java.lang.CharSequence MetaDataPath;
  @Deprecated public java.lang.CharSequence SampleDataPath;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public FileMetaData() {}

  /**
   * All-args constructor.
   * @param JobId The new value for JobId
   * @param MetaDataPath The new value for MetaDataPath
   * @param SampleDataPath The new value for SampleDataPath
   */
  public FileMetaData(java.lang.CharSequence JobId, java.lang.CharSequence MetaDataPath, java.lang.CharSequence SampleDataPath) {
    this.JobId = JobId;
    this.MetaDataPath = MetaDataPath;
    this.SampleDataPath = SampleDataPath;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return JobId;
    case 1: return MetaDataPath;
    case 2: return SampleDataPath;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: JobId = (java.lang.CharSequence)value$; break;
    case 1: MetaDataPath = (java.lang.CharSequence)value$; break;
    case 2: SampleDataPath = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'JobId' field.
   * @return The value of the 'JobId' field.
   */
  public java.lang.CharSequence getJobId() {
    return JobId;
  }

  /**
   * Sets the value of the 'JobId' field.
   * @param value the value to set.
   */
  public void setJobId(java.lang.CharSequence value) {
    this.JobId = value;
  }

  /**
   * Gets the value of the 'MetaDataPath' field.
   * @return The value of the 'MetaDataPath' field.
   */
  public java.lang.CharSequence getMetaDataPath() {
    return MetaDataPath;
  }

  /**
   * Sets the value of the 'MetaDataPath' field.
   * @param value the value to set.
   */
  public void setMetaDataPath(java.lang.CharSequence value) {
    this.MetaDataPath = value;
  }

  /**
   * Gets the value of the 'SampleDataPath' field.
   * @return The value of the 'SampleDataPath' field.
   */
  public java.lang.CharSequence getSampleDataPath() {
    return SampleDataPath;
  }

  /**
   * Sets the value of the 'SampleDataPath' field.
   * @param value the value to set.
   */
  public void setSampleDataPath(java.lang.CharSequence value) {
    this.SampleDataPath = value;
  }

  /**
   * Creates a new FileMetaData RecordBuilder.
   * @return A new FileMetaData RecordBuilder
   */
  public static com.pharbers.kafka.schema.FileMetaData.Builder newBuilder() {
    return new com.pharbers.kafka.schema.FileMetaData.Builder();
  }

  /**
   * Creates a new FileMetaData RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new FileMetaData RecordBuilder
   */
  public static com.pharbers.kafka.schema.FileMetaData.Builder newBuilder(com.pharbers.kafka.schema.FileMetaData.Builder other) {
    return new com.pharbers.kafka.schema.FileMetaData.Builder(other);
  }

  /**
   * Creates a new FileMetaData RecordBuilder by copying an existing FileMetaData instance.
   * @param other The existing instance to copy.
   * @return A new FileMetaData RecordBuilder
   */
  public static com.pharbers.kafka.schema.FileMetaData.Builder newBuilder(com.pharbers.kafka.schema.FileMetaData other) {
    return new com.pharbers.kafka.schema.FileMetaData.Builder(other);
  }

  /**
   * RecordBuilder for FileMetaData instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<FileMetaData>
    implements org.apache.avro.data.RecordBuilder<FileMetaData> {

    private java.lang.CharSequence JobId;
    private java.lang.CharSequence MetaDataPath;
    private java.lang.CharSequence SampleDataPath;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.pharbers.kafka.schema.FileMetaData.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.JobId)) {
        this.JobId = data().deepCopy(fields()[0].schema(), other.JobId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MetaDataPath)) {
        this.MetaDataPath = data().deepCopy(fields()[1].schema(), other.MetaDataPath);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.SampleDataPath)) {
        this.SampleDataPath = data().deepCopy(fields()[2].schema(), other.SampleDataPath);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing FileMetaData instance
     * @param other The existing instance to copy.
     */
    private Builder(com.pharbers.kafka.schema.FileMetaData other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.JobId)) {
        this.JobId = data().deepCopy(fields()[0].schema(), other.JobId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.MetaDataPath)) {
        this.MetaDataPath = data().deepCopy(fields()[1].schema(), other.MetaDataPath);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.SampleDataPath)) {
        this.SampleDataPath = data().deepCopy(fields()[2].schema(), other.SampleDataPath);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'JobId' field.
      * @return The value.
      */
    public java.lang.CharSequence getJobId() {
      return JobId;
    }

    /**
      * Sets the value of the 'JobId' field.
      * @param value The value of 'JobId'.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.FileMetaData.Builder setJobId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.JobId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'JobId' field has been set.
      * @return True if the 'JobId' field has been set, false otherwise.
      */
    public boolean hasJobId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'JobId' field.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.FileMetaData.Builder clearJobId() {
      JobId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'MetaDataPath' field.
      * @return The value.
      */
    public java.lang.CharSequence getMetaDataPath() {
      return MetaDataPath;
    }

    /**
      * Sets the value of the 'MetaDataPath' field.
      * @param value The value of 'MetaDataPath'.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.FileMetaData.Builder setMetaDataPath(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.MetaDataPath = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'MetaDataPath' field has been set.
      * @return True if the 'MetaDataPath' field has been set, false otherwise.
      */
    public boolean hasMetaDataPath() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'MetaDataPath' field.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.FileMetaData.Builder clearMetaDataPath() {
      MetaDataPath = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'SampleDataPath' field.
      * @return The value.
      */
    public java.lang.CharSequence getSampleDataPath() {
      return SampleDataPath;
    }

    /**
      * Sets the value of the 'SampleDataPath' field.
      * @param value The value of 'SampleDataPath'.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.FileMetaData.Builder setSampleDataPath(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.SampleDataPath = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'SampleDataPath' field has been set.
      * @return True if the 'SampleDataPath' field has been set, false otherwise.
      */
    public boolean hasSampleDataPath() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'SampleDataPath' field.
      * @return This builder.
      */
    public com.pharbers.kafka.schema.FileMetaData.Builder clearSampleDataPath() {
      SampleDataPath = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    public FileMetaData build() {
      try {
        FileMetaData record = new FileMetaData();
        record.JobId = fieldSetFlags()[0] ? this.JobId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.MetaDataPath = fieldSetFlags()[1] ? this.MetaDataPath : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.SampleDataPath = fieldSetFlags()[2] ? this.SampleDataPath : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

}
